name: Publish Package

on:
  release:
    types: [created]

jobs:
  npmrc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        always-auth: true
        node-version: '14.x'
        registry-url: https://registry.npmjs.org
        scope: '@mike-han'
    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  build:
    runs-on: ubuntu-latest
    needs: npmrc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
      - run: npm publish --access publich
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
